language: node_js
node_js:
  - '14'
before_script:
  - npm install gulp
  - npm install gulp --save-dev
  - npm i gulp-inline-source 
script: gulp inlinesource
after_script:
  - .travis/push.sh
env:
  global:
    secure: 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
